services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./src/apps/web/Dockerfile
    restart: always
    ports:
      - "8080:80"
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./src/apps/api/Dockerfile
    restart: always
    ports:
      - "3001:3001"