onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - normalize-diacritics

packages:
  # Repository root
  - '.'
  # Deployable apps (e.g. Node.js, React)
  - 'src/apps/*'
  # Shared runtime code (e.g. UI components, utils)
  # - 'src/packages/*'
  # Development-only tooling (e.g. configs, linters, build tools)
  - 'src/dev/*'
   
strictPeerDependencies: true