import { z as zod } from "zod";

export const ConceptSchema = (z: typeof zod) =>
  z.object({
    index: z.coerce.number(),
    key: z.string(),
  });
export type Concept = zod.infer<ReturnType<typeof ConceptSchema>>;

export const CityLabelSchema = (z: typeof zod) =>
  z
    .object({
      cluster_id: z.coerce.number(),
      label: z.string(),
    })
    .transform((data) => ({
      clusterId: data.cluster_id,
      label: data.label,
    }));
export type CityLabel = zod.infer<ReturnType<typeof CityLabelSchema>>;

export const DataSchema = (z: typeof zod, labels: Map<number, CityLabel>) =>
  z
    .object({
      cluster_id: z.coerce.number(),
      x: z.coerce.number(),
      y: z.coerce.number(),
      num_recent_articles: z.coerce.number(),
      cluster_category: z.coerce.number(),
      growth_rating: z.coerce.number(),
      key_concepts: z.string(),
    })
    .transform((data) => ({
      clusterId: data.cluster_id,
      x: data.x,
      y: -data.y, // To align it with the map coordinate system
      numRecentArticles: data.num_recent_articles,
      clusterCategory: data.cluster_category,
      growthRating: data.growth_rating,
      keyConcepts: data.key_concepts.split(",").map((id) => Number(id)),
      cityLabel: labels.get(data.cluster_id)?.label ?? null,
    }));
export type DataPoint = zod.infer<ReturnType<typeof DataSchema>>;

// TODO: All these will be present in the CSV.
// We keep it here just for PoC purposes.
const LABELS = [
  "Symbole-bity-sygnały",
  "Społeczeństwo",
  "Życie człowieka",
  "Medycyna",
  "Chemia",
  "Biologia",
  "Wytwarzanie",
  "Fizyka",
  "Ziemia",
  "Komputery i komunikacja",
  "Bakterie i choroby zakaźne",
  "Tekst i tłumaczenie",
  "Rozmnażanie ludzi i zwierząt",
  "Problemy społeczne",
  "Pieniądze",
  "Rodzina, młodość i seks",
  "Biznes",
  "Język",
  "Wiedza i edukacja",
  "Umysł i zdrowie",
  "Mózg i zdrowie psychiczne",
  "Matematyka",
  "Fizyka teoretyczna",
  "Fotonika",
  "Urazy i ortopedia",
  "Kosmos",
  "Litosfera",
  "Fizyka jądrowa",
  "Paliwa i odpady",
  "Rośliny",
  "Hodowla zwierząt",
  "Ekologia i ochrona środowiska",
  "Biologia organizmów",
  "Gleba, woda, biosfera",
  "Materiały",
  "Woda i odpady",
  "Terapeutyka molekularna",
  "Materiały miękkie i biokompatybilne",
  "Żywność",
  "Beton",
  "Nanotechnologia i elektronika",
  "Technologie produkcyjne",
  "Biologia komórki",
  "Nowotwory",
  "Serce i układ krążenia",
  "Chirurgia",
  "DNA i genom",
  "Chemia organiczna",
  "Sport i sprawność",
  "Zawód medyczny",
  "Ciąża i noworodki",
  "Makrocząstki",
  "Intensywna terapia",
  "Algorytmy i roboty",
  "Budynki i transport",
  "Rynki i rządy",
  "Maszyny",
  "Ból",
  "Fotochemia organiczna",
  "Skażenie środowiska",
  "Choroby zapalne",
  "Państwo i władza",
  "Historia i kultura",
  "Urządzenia mechaniczne",
  "Robotyka",
  "Chłodzenie i energia cieplna",
  "Energia odnawialna",
  "Hydrodynamika: wiry, turbulencja, symulacje",
  "Anteny mikrofalowe i detekcja fal elektromagnetycznych",
  "Metamateriały akustyczne i mechaniczne",
  "Sieć elektryczna, smart grid, ładowanie pojazdów elektrycznych",
  "Lotnictwo",
  "Aerodynamika, turbiny wiatrowe i lotnictwo",
  "Energetyka: systemy dystrybucji",
  "Komponenty dla robotyki: akcelerometry, MEMS",
  "Technologie satelitarne",
  "Astrofizyka gwiazdowa i galaktyczna",
  "Kosmologia i astronomia obserwacyjna",
  "Fizyka cząstek",
  "Kosmologia relatywistyczna",
  "Metamateriały fotoniczne",
  "Obrazowanie, hologramy, wyświetlacze",
  "Lasery, sygnały wysokiej częstotliwości",
  "Wiatr słoneczny i magnetosfery",
  "Asteroidy i wietrzenie kosmiczne",
  "Podstawy fizyki kwantowej",
  "Energetyka jądrowa",
  "Wytwarzanie i manipulowanie strumieniami cząstek",
  "Podstawy fizyki jądrowej",
  "Komunikacja optyczna",
  "Asfalt",
  "Wydobywanie węglowodorów",
  "Naturalna promieniotwórczość",
  "Konstrukcje betonowe",
  "Beton zbrojony i kompozytowy",
  "Cement i inne składniki betonu",
  "Geologia regionalna i złożowa",
  "Tektonika i sejsmologia",
  "Górnictwo i petrologia",
  "Stabilność gruntu, osuwiska, gleby",
  "Atmosfera i klimat",
  "Opady i powodzie",
  "Roślinność, lasy, pożary",
  "Badania satelitarne",
  "Lodowce",
  "Rzeki, wody gruntowe i gleby",
  "Roślinność, lasy, pożary",
  "Zanieczyszczenie powietrza",
  "Ewolucja człowieka, początki cywilizacji",
  "Świat starożytny",
  "Świat nowożytny",
  "Świat współczesny",
  "Wojny i konflikty",
  "Władza i polityka",
  "Prawo międzynarodowe",
  "Media i dziennikarstwo",
  "Ludzkie życie seksualne",
  "Mniejszości seksualne",
  "Edukacja",
  "Rolnictwo i rynek żywności",
  "Rynek mieszkaniowy, zarządzanie miastami",
  "Turystyka",
  "Polityka środowiskowa",
  "Inżynieria i prawo budowlane",
  "Transport samochodowy, komunikacja miejska",
  "Zarządzanie i logistyka budownictwa",
  "Komputerowa analiza tekstu",
  "Tłumaczenie",
  "Analiza treści w mediach społecznościowych",
  "Praca",
  "Klienci-marki-usługi",
  "Zarządzanie przedsiębiorstwem",
  "Produkcja i logistyka",
  "Przedsiębiorczość",
  "Filozofia",
  "Sektor publiczny i prywatny",
  "Giełda i ekonomia behawioralna",
  "Podatki",
  "Globalny rynek i polityka",
  "Rozwój ekonomiczny",
  "Zrównoważony rozwój",
  "Świat sportu",
  "Druk 3D metali i kompozytów",
  "Obróbka produktów, smarowanie",
  "Tranzystory, diody i okolice",
  "Kubity, kropki kwantowe i okolice",
  "Nanowstążki, heterostruktury van der Waalsa i okolice",
  "Izolatory topologiczne i okolice",
  "Cienkie warstwy i nanoelektronika",
  "Silniki i spalanie",
  "Biomasa, ścieki, spalanie śmieci",
  "Materiały ceramiczne",
  "Ogniwa fotowoltaiczne i perowskity",
  "Ogniwa paliwowe",
  "Nanopręciki i cienkie warstwy ZnO",
  "Materiały do czujników gazu",
  "Baterie i elektrody",
  "Elektronika miękka, smart textiles",
  "Wytwarzanie addytywne (przyrostowe)",
  "Żywice, kompozyty, piany, włókna",
  "Materiały ognioodporne",
  "Ciekłe kryształy",
  "Teoria funkcjonału gęstości (DFT)",
  "Materiały katalityczne",
  "Drewno",
  "Urządzenia osmotyczne",
  "Materiały sypkie",
  "Płomienie i turbulencja",
  "Materiały aktywne powierzchniowo",
  "Membrany filtracyjne",
  "Bioreaktory, odpady aktywne chemicznie",
  "Organiczne LEDy i ogniwa fotowoltaiczne",
  "Efekty świetlne w materiałach organicznych",
  "Fotochemia farmaceutyczna",
  "Mikrofluidyka i nanocząstki",
  "Inżynieria tkankowa i biomedyczna",
  "Lignina i celuloza",
  "Hydrożele, robotyka miękka",
  "Technologia żywności",
  "Mikro- i nanotechnologie dostarczania leków",
  "Nanotechnologia w terapii onkologicznej",
  "Chemia syntetyczna",
  "Mechanizmy reakcji chemicznych",
  "Odkrywanie leków i mechanizmy ich działania",
  "Białka",
  "Struktury RNA i DNA",
  "Genetyka molekularna",
  "Genomika",
  "Produkty roślinne i ich przetwarzanie",
  "Produkty naturalne w medycynie",
  "Produkty zwierzęce i ich przetwarzanie",
  "Spektroskopia Ramana",
  "Choroby grzybicze",
  "Zęby",
  "HIV",
  "Nowotwory krwi",
  "Helicobacter pylori",
  "Nowotwory płuc, inne",
  "Nowotwory wątroby i inne",
  "Rak sutka i inne",
  "Genomika i biochemia nowotworów",
  "Biologia komórki nowotworowej",
  "Procesy komórkowe",
  "Komórki macierzyste",
  "Choroby układu oddechowego",
  "Słuch i równowaga",
  "Odżywianie osób chorych i starszych",
  "Zapalenie stawów",
  "Choroby skóry",
  "Zapalenie jelit",
  "Zapalenie wątroby",
  "Nowotwory tkanek miękkich i inne",
  "Operacje układu pokarmowego",
  "Operacje wyrostka i bariatryczne",
  "Chirurgia piersi",
  "Cukrzyca",
  "Przeszczepy",
  "Nadciśnienie",
  "Choroba niedokrwienna serca",
  "Rytm serca",
  "Chirurgia układu krążenia",
  "Choroby naczyń krwionośnych",
  "Operacje wad wrodzonych",
  "Psychologia ciąży",
  "Poród i opieka nad noworodkami",
  "Zdrowie kobiety w ciąży",
  "Koronawirus",
  "Bezdech senny",
  "Ostra niewydolność oddechowa",
  "Nagłe zatrzymanie krążenia",
  "Tarczyca",
  "Anemia, talasemia, żelazo",
  "Anestezjologia i opieka pooperacyjna",
  "Ból przewlekły",
  "Zarządzanie bólem",
  "Ból głowy",
  "Kręgosłup",
  "Urazy i ich leczenie operacyjne",
  "Urazy kolana",
  "Gruźlica",
  "Infekcje i antybiotyki",
  "Mikrobiom jelitowy",
  "Różne choroby wirusowe i bakteryjne",
  "Choroby przenoszone drogą płciową",
  "Zaburzenia psychiczne",
  "Sieci funkcjonalne mózgu",
  "Procesy poznawcze człowieka",
  "Dietetyka",
  "Oczy i widzenie",
  "Zdrowie gleby, kompost",
  "Choroby tropikalne",
  "Bisfenol, PFAS i inne",
  "Grzyby",
  "Ekologia i zachowania zwierząt",
  "Ekosystemy dna oceanu",
  "Życie w oceanach i rybołówstwo",
  "Jakość wody, mikroorganizmy wodne",
  "Biogeografia",
  "Pestycydy",
  "Metale ciężkie w środowisku",
  "Wzrost i odporność roślin na stres",
  "Hodowla ryb",
  "Owady",
  "Genetyka organizmów i populacji",
  "Choroby tropikalne",
  "Zespół policystycznych jajników",
  "Embriologia i sztuczne zapłodnienie",
  "Malaria",
  "Konie i zwierzęta domowe",
  "Bydło domowe",
  "Drób",
  "Choroby roślin",
  "Biomechanika ruchu",
  "Trening specjalistyczny",
  "Sprawność w chorobie i starości",
  "Psychologia sportu",
  "Zdrowie psychiczne",
  "Uzależnienia od substancji",
  "Aktywność fizyczna",
  "Starość",
  "Edukacja medyczna",
  "Farmaceutyka",
  "Opieka nad osobami starszymi i hospicyjna",
  "Ach, ci pacjenci",
  "Zaburzenia snu",
  "Przestępczość",
  "Ideologie, uprzedzenia, konflikty",
  "Przemoc",
  "Autyzm",
  "Edukacja matematyczna",
  "Technologie cyfrowe w edukacji",
  "Szkoła islamska",
  "Publikowanie naukowe",
  "Edukacja językowa",
  "Teoria języka",
  "Obraz ciała, zaburzenia odżywiania",
  "Palenie",
  "Analiza dźwięku i mowy",
  "Cyberbezpieczeństwo",
  "Obliczanie rozproszone-IoT-blockchain",
  "Usługi chmurowe i edge computing",
  "Sieci bezprzewodowe",
  "Szyfrowanie danych",
  "Uczenie maszynowe",
  "Roboty i drony autonomiczne",
  "Teoria sterowania",
  "Równania różniczkowe i układy dynamiczne",
  "Matematyka uczenia maszynowego",
  "Analiza zespolona-geometria-topologia",
  "Algebra",
  "Logika rozmyta",
  "Kombinatoryka",
  "Analiza danych, systemy decyzyjne",
  "Osobowość i różnice międzyosobnicze zwierząt",
  "Spektroskopia LIBS",
  "Generowanie wyższych harmonicznych",
  "Plazma niskotemperaturowa",
  "Laserowa spektroskopia absorpcyjna",
  "Kwantowe układy optomechaniczne",
  "Obliczenia kwantowe w układach fotonicznych",
  "Fotonika topologiczna",
  "Szerokopasmowe absorbery metamateriałowe",
  "Lasery włóknowe wysokiej mocy",
  "Czujniki światłowodowe",
  "Rozproszone wykrywanie akustyczne (DAS)",
  "Kubity nadprzewodnikowe",
  "Magnetometry pompowane optycznie (OPM)",
  "Metapowierzchnie i metasoczewki",
  "Orbitalny moment pędu światła",
  "Metamateriały termiczne",
  "Podwodna komunikacja bezprzewodowa",
  "Obrazowanie w ośrodkach rozpraszających",
  "Wyświetlacze holograficzne",
  "Materia aktywna",
  "Anosmia i inne zaburzenia węchu",
  "Substancje psychodeliczne",
  "Ketamina i esketamina w leczeniu depresji",
  "Mikrobiom w depresji i innych zaburzeniach psychicznych",
  "Mikroglej",
  "Epigenetyczne markery starzenia",
  "Kannabidiol (CBD)",
  "Głębokie sieci neuronowe w badaniach Alzheimera",
  "Przezczaszkowa stymulacja prądem stałym (tDCS)",
  "Obrazowanie mózgu podczas wyobrażania ruchowego",
  "Rozpoznawanie emocji na podstawie EEG",
  "Poczucie ciała w wirtualnej rzeczywistości",
  "Hydrożele przewodzące",
  "Hydrożele w leczeniu ran",
  "Druk 3D materiałów biologicznych i biokompatybilnych",
  "Druk 4D i materiały aktywne",
  "Dynamika polimerów, polimery samoleczące, witrymery",
  "Inżynieria chemiczna ligniny w bioraniferiach",
  "Nanokryształy celulozy (CNC)",
  "Inżynieria chemiczna biomasy drzewnej",
  "Materiały i związki pochodzenia naturalnego w produkcji opakowań",
];

const randomInt = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min + 1)) + min;

export const YoutubeVideoSchema = (z: typeof zod) =>
  z
    .object({
      video_id: z.string(),
      video_title: z.string(),
      date: z.string().datetime(),
      segment_number: z
        .string()
        .regex(/^\d+\)$/)
        .transform((val) => Number(val)),
      segment_timestamp: z.string(),
      segment_url: z.string().url(),
      segment_topic: z.string(),
      reference: z.string(),
      article_link: z.string().url(),
      segment_name: z.string(),
    })
    .transform((data) => ({
      videoId: data.video_id,
      videoTitle: data.video_title,
      date: data.date,
      segmentNumber: data.segment_number,
      segmentTimestamp: data.segment_timestamp,
      segmentUrl: data.segment_url,
      segmentTopic: data.segment_topic,
      reference: data.reference,
      articleLink: data.article_link,
      segmentName: data.segment_name,
      // TODO: Just a temp solution to have some labels.
      labelIds: [
        ...new Set(
          Array.from(
            { length: randomInt(1, 3) },
            () => LABELS[randomInt(0, LABELS.length - 1)],
          ),
        ).values(),
      ],
    }));
export type YoutubeVideo = zod.infer<ReturnType<typeof YoutubeVideoSchema>>;
